FROM python:3.11-slim
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
EXPOSE 8501
CMD ["streamlit", "run", "main.py", "--server.address=0.0.0.0"]

#CMD ["streamlit", "run", "main.py", \
#    "--server.port=8501", \
#    "--server.address=0.0.0.0", \
#    "--server.enableCORS=false", \
#    "--server.headless=true", \
#    "--server.baseUrlPath="]
