services:
  flask:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: flask_api
    ports:
      - "5000:5000"

  streamlit:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    depends_on:
      - flask