services:
  flask:
    build: ./api
    container_name: flask_api
    ports:
      - "5000:5000"

  streamlit:
    build: ./frontend
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    depends_on:
      - flask
