apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20   # tempo de espera (em segundos) antes de reduzir pods
      policies:
        - type: Percent
          value: 50
          periodSeconds: 20
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 1
          periodSeconds: 20

# deixei scaleup definido abaixo para testar - ele está restringindo quantos pods (11) podem escalar em um determinado tempo (20s). verificar se assim é ok, ou se volto para a medida anterior que nao tem restrição
# de repente manter só a definicao de scaleDown em behavior
