name: On-Premise Pipeline

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  on-prem:
    name: On-Premise CI on Self-Hosted Runner
    runs-on: self-hosted

    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Verificar/Instalar Python 3.11
        run: |
          $python = Get-Command python3.11 -ErrorAction SilentlyContinue
          if ($python) {
            Write-Host "✅ Python 3.11 já está instalado: $(python3.11 --version)"
          } else {
            Write-Host "⚠️ Python 3.11 não encontrado. Instalando com setup-python..."
            "python-version=3.11" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            "needs_python_install=true" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          }

      - name: Configurar Python com setup-python
        if: env.needs_python_install == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Criar e ativar ambiente virtual, instalar dependências
        working-directory: ./api
        run: |
          if (-Not (Test-Path ".venv")) {
            python -m venv .venv
          }

          .\.venv\Scripts\Activate.ps1

          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com pytest
        working-directory: ./api
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest -v ../tests/


      - name: Build das imagens com Docker Compose
        run: |
          docker-compose build


      - name: Subir cluster local e expor com ngrok
        run: |
          .\local_dev.ps1
