name: On-Premise Pipeline

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  on-prem:
    name: On-Premise CI on Self-Hosted Runner
    runs-on: self-hosted

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Verificar/Instalar Python 3.11
        run: |
          if command -v python3.11 &>/dev/null; then
            echo "✅ Python 3.11 já está instalado: $(python3.11 --version)"
          else
            echo "⚠️ Python 3.11 não encontrado. Instalando com setup-python..."
            echo "python-version=3.11" >> $GITHUB_ENV
            echo "needs_python_install=true" >> $GITHUB_ENV
          fi

      - name: Configurar Python com setup-python
        if: env.needs_python_install == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Criar e ativar ambiente virtual, instalar dependências
        working-directory: ./api
        run: |
          if [ ! -d ".venv" ]; then
            python3.11 -m venv .venv
          fi

          source .venv/bin/activate || source .venv/Scripts/activate

          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com pytest
        working-directory: ./api
        run: |
          source .venv/bin/activate || source .venv/Scripts/activate
          pytest -v tests/

      - name: Build das imagens com Docker Compose
        run: |
          docker-compose build
